### ISSUE TITLE
Hash URL en inscripción me lleva al curso seleccionado

### ISSUE THREAD

**Issue by lucasromerodb** [innatus/innatus-web-design#2]
El JS de inscripcion levanta el #xxx de la url y activa el curso en la parte de selección. 
El problema es que si la url tiene un #, éste te lleva hasta esa parte del html.
Se solucionaría con un: $(window).scrollTop(0); pero hay algúna definición en el lib.js que hace que cuando el documento vaya arriba de todo, la nav desaparezca.

**Comment by lucasromerodb** [comment]
parcheado provisoriamente en vform.js :

if (location.hash) {
        window.scrollTo(0, 10);
    $('html, body').animate({
        'scrollTop': 0
    }, 300);
}

**Comment by nicolasdanelon** [comment]
eso puede afectar las demás páginas... mejor sería pasar como parametro un array de los posibles lotation.hash y compararlos, no?
http://api.jquery.com/jQuery.inArray/
